version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nanuri-backend
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/run_server.sh
      timeout: 600
      runas: root
