version: "3"

volumes:
  local_db_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ".env"
    volumes:
      - .:/code:z
    ports:
      - "8000:8000"
    working_dir: /code
    command: |
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:12.9
    env_file:
      - ".env"
    volumes:
      - local_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
