version: "3"

volumes:
  local_db_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ".env"
    volumes:
      - ".:/code:z"
    ports:
      - "8080:8080"
    working_dir: /code
    command: >
      sh -c "python manage.py collectstatic --no-input && daphne -b 0.0.0.0 -p 8080 config.asgi:application"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:12.9
    env_file:
      - ".env"
    volumes:
      - local_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:5
    ports:
      - "6379:6379"
    restart: always
