# Generated by Django 3.2.12 on 2022-03-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('APPLE', '애플'), ('KAKAO', '카카오')], default=True, max_length=15, null=True),
        ),
    ]
