# Generated by Django 3.2.12 on 2022-03-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220331_0720'),
        ('users', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_posts',
            field=models.ManyToManyField(related_name='favored_by', to='posts.Post'),
        ),
    ]
