# Generated by Django 3.2.12 on 2022-04-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_favorite_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('APPLE', '애플'), ('KAKAO', '카카오')], default=None, max_length=15, null=True),
        ),
    ]
