# Generated by Django 3.2.15 on 2022-09-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
