# Generated by Django 3.2.13 on 2022-04-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakaoaccount',
            name='kakao_id',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
