# Generated by Django 3.2.13 on 2022-04-26 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_kakaoaccount_kakao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakaoaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kakaoaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
