# Generated by Django 3.2.13 on 2022-07-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_postimage_uuid'),
        ('notifications', '0002_device_endpoint_arn'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('device', 'post', 'topic')},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='receive_chat_messages',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='receive_comments',
        ),
    ]
