# Generated by Django 3.2.15 on 2022-09-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_device_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
    ]
