# Generated by Django 3.2.13 on 2022-04-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220407_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order_status',
            field=models.CharField(choices=[('ADVERTISING', '인원 모집 중'), ('ORDERING', '주문 진행 중'), ('ORDERED', '주문 완료'), ('DELIVERING1', '1차 배송 중'), ('DELIVERING2', '2차 배송 중'), ('DELIVERED', '배송 완료'), ('CANCELLED', '취소됨')], default='ADVERTISING', max_length=15),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
