# Generated by Django 3.2.13 on 2022-04-15 10:06

from django.db import migrations, models
import django.db.models.deletion
import nanuri.posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, unique=True, upload_to=nanuri.posts.models.Post.upload_to),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, unique=True, upload_to=nanuri.posts.models.PostImage.upload_to)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
        ),
    ]
