# Generated by Django 3.2.13 on 2022-04-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220418_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='order_status',
            field=models.CharField(choices=[('WAITING', '인원 모집 중'), ('ORDERING', '주문 진행 중'), ('ORDERED', '주문 완료'), ('DELIVERING1', '1차 배송 중'), ('DELIVERING2', '2차 배송 중'), ('DELIVERED', '배송 완료'), ('CANCELLED', '취소됨')], default='WAITING', max_length=15),
        ),
    ]
