# Generated by Django 3.2.13 on 2022-04-20 15:12

from django.db import migrations, models
import django.db.models.deletion
import nanuri.posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=nanuri.posts.models.Post.upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='waited_from',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='waited_until',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=nanuri.posts.models.PostImage.upload_to),
        ),
    ]
