# Generated by Django 3.2.13 on 2022-07-17 04:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220705_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid'),
        ),
    ]
