# Generated by Django 3.2.14 on 2022-08-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_postimage_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('BATHROOM', '욕실'), ('FOOD', '음식'), ('KITCHEN', '주방'), ('HOUSEHOLD', '생활용품'), ('STATIONERY', '문구'), ('ETC', '기타')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
