# Generated by Django 3.2.13 on 2022-07-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='endpoint_arn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
