# Generated by Django 3.2.13 on 2022-04-28 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_auto_20220426_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakaoaccount',
            name='kakao_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='kakaoaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
